### ISSUE TITLE
Update links prior to hitting submit

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#10]
## User Story
As a wrangler I would like to update links within a submission prior to submitting it when I find an error or missed something, currently I have to delete the submission and start again, which is very slow.

add new linking

## Acceptance Criteria
Provide a way to update linking between metadata entities in a submission

**Comment by aaclan-ebi** [comment]
Tasks:
    a. (New ticket) Create a UI component to display and update the inputs and outputs of an entity
      - add buttons for adding and removing links
    b. (New ticket) Add endpoints in Core to add and update links

**Comment by aaclan-ebi** [comment]
Additional tickets:
1. [Core] Create search endpoints to search protocols, process, files
2. [UI]  (New ticket) Create a UI component to display and update the inputs and outputs of an entity
- component to search entities
- page/workspace containing add buttons for adding and removing links

**Comment by rays22** [comment]
* [TEST CASE ID: U2](https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/edit#gid=0) : **FAIL**

It seems that I can add new entities in under the `Processes` tab, provided that the entity has been already loaded into Ingest from the current or another unrelated submission. By unrelated submission I meant that a submission to a project that is different from the current project I am working on.
The graph is updated under the `Processes` tab and it does show the newly linked entity.
However, the new entity does not show up under any other tab. For example, if I add a new biomaterial, it will not be displayed under the `Biomaterals` tab. Moreover, if I delete the original entity, then it will be flagged as orphan  under the appropriate tab and I have found no way to dissociate it from the project/submission. If that entity is not going to be exported because of being an orphaned entity, then it may be the desired outcome, but it is still confusing.
I can remove one, two ... all the linked entities from a process and the submission status still remains `Valid`.

If the scope of the test U2 were only to check if the updates work under the `Processes` tab, then the test outcome would be a `PASS`. However, when I look further and check the other tabs related to the edited entities, then the results are very confusing and I am not sure if that is the expected outcome after editing the links.

**Comment by aaclan-ebi** [comment]
Hi @rays22 ! Thanks so much for testing this yesterday (even if it's already a bit late in normal work hours )and giving this feedback to us before your holiday! Much appreciated! :)

> It seems that I can add new entities in under the Processes tab, provided that the entity has been already loaded into Ingest from the current or another unrelated submission. By unrelated submission I meant that a submission to a project that is different from the current project I am working on.

Yes, you can search an entity by their metadata id (e.g. `biomaterial_core. biomaterial_id`). Bear in mind that this is not unique across all projects. So the search result can return entities from different submissions/projects. I think @gabsie suggested before that it should be entities from within same project. @clairerye could you also confirm this?

> The graph is updated under the Processes tab and it does show the newly linked entity.
However, the new entity does not show up under any other tab. For example, if I add a new biomaterial, it will not be displayed under the Biomaterals tab. 

Yes, if you link the process to an entity previously created from a different submission it doesn't mean that that linked entity will show in the current submission. The entities which only appears in current submission are entities created with that submission.

> Moreover, if I delete the original entity, then it will be flagged as orphan under the appropriate tab and I have found no way to dissociate it from the project/submission. If that entity is not going to be exported because of being an orphaned entity, then it may be the desired outcome, but it is still confusing.

There is no way to delete a metadata from a submission yet. That will be in a different user story. ebi-ait/dcp-ingest-central#31

> I can remove one, two ... all the linked entities from a process and the submission status still remains Valid.
When you remove entities from a process, it doesn't mean you are removing it from the submission, you are just unlinking it from the process. It may be clearer to change the button labels to _Link_ and _Unlink_ instead of _Add_ and _Remove_ . Also the validity of a submission currently means that all entities created by that submission has a valid metadata and data. Sadly, it doesn't do any further validation on linking yet. That can be for another user story ticket.

> If the scope of the test U2 were only to check if the updates work under the Processes tab, then the test outcome would be a PASS. However, when I look further and check the other tabs related to the edited entities, then the results are very confusing and I am not sure if that is the expected outcome after editing the links.

Good points, @rays22 . The scope of this ticket is to really just update the linking between metadata entities in and experiment (biomaterials, processes, protocols and files). Some concerns/functionalities needed should be addressed in other user stories.

**Comment by aaclan-ebi** [comment]
We'll look into further **filtering the search results to only contain entities from the same project** or **just displaying the project detail when searching for entities to guide the user to select entity to link to** (in case filtering will need more time to implement for this sprint). 

@gabsie @clairerye could you also confirm that this makes sense for the users?

**Comment by aaclan-ebi** [comment]
Just a quick heads up, we've discussed this further among devs ( @jacobwindsor  @prabh-t ) and we figured out that it'd be a bit difficult to filter the entities to only contain entities in the same project given the way things are modelled. We'll aim to filter the search result by submission envelope instead of the project for this sprint. @clairerye we can discuss this later at 1.30pm on our catchup.

**Comment by clairerye** [comment]
In discussion we agreed we would filter the search result by submission envelope instead of the project for this sprint.

**Comment by aaclan-ebi** [comment]
@gabsie here's the user story ticket for updating links between entities

**Comment by clairerye** [comment]
I think we may be best to combine all the stories from this impact that we have been working on as I think they fit together nicely in Gabs' 'Review and repair' feature. There were some good suggestions brought up by Enrique, Oihane and Marion which can be included in going through them all together and aligning the feedback.

**Comment by clairerye** [comment]
Currently with the bug reported here - Filter entities when searching to update links  (#219) and so it is still easier to delete a submission and re-upload the spreadsheet than identify the entities that need to be changed.

**Comment by gabsie** [comment]
This is resolved with our metadata linking updates.
