### ISSUE TITLE
AIT soil sample and data submission

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/dcp-ingest-central#1022]
- [x] Contact Stefan (MUG) to check on the following:

Should [PRJEB74630](https://www.ebi.ac.uk/ena/browser/view/PRJEB74630) be public? 
Should [SAMEA115414644](https://www.ebi.ac.uk/ena/browser/view/SAMEA115414644) be associated with 6 read files?

- [x] The samples under PRJEB74630 need updating:
Dipayan registered these4 samples  - they need ‘project’ attribute updated to ‘project name’. 
Also need validating against GSC soil Check read data has been associated with these

- [x] Link PRJEB74630 to the MICROBE umbrella

**Comment by ESapenaVentura** [comment]
I have sent an email to Stefan about the project:
- Project is intended to be public
- That sample is associated with 6 runs - They had to cut the files due to upload errors. Asked them if they want to re-upload, and they said that due to time, they would prefer to not re-upload and re-submit. Apparently they used lftp, so I may suggest using Aspera next time (I think it works better for large file uploads)

The project has been linked to the [umbrella project](https://www.ebi.ac.uk/ena/browser/view/PRJEB74917)

Just need to update the samples now!

**Comment by ESapenaVentura** [comment]
The samples can't be updated by me - I get a "forbidden" erorr. I should check with Dipayan to check what account was used

**Comment by ESapenaVentura** [comment]
Dipayan transferred the sample ownership to myself and I have updated the samples - All done here!
