### ISSUE TITLE
Capturing contributor matrices

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/dcp-ingest-central#129]
## User story
As a wrangler I want contributor matrices and relevant associated metadata accurately captured by the HCA metadata schema so that they can be used by data consumers

## Acceptance Criteria

- [x] decision on schema changes to contributor matrices made
- [x] summary of these changes shared with DCP (not a big proposal)
- [x] refinement based on feedback
- [ ] SOP for wrangling updated to reflect this
- [ ] changes made to the schema (stretch goal)

Decisions need to be made about how we capture contributor matrices

The portal team is keen to get feedback on their existing solutions for matrices from the standard processing pipeline and if this could be reused for the contributor matrices too. This is from Hannes in the MVP specification document https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.90wk76br22na

> This project has those graphs but it is a WIP (it currently shows too many matrix files):
> 
> https://dev.singlecell.gi.ucsc.edu/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803/expression-matrices?catalog=dcp2
> 
> The best way to look at it is using the staging areas that
> 
> @jway@broadinstitute.org @gwade@broadinstitute.org
> @kdegatano@broadinstitute.org
> 
> set up:
> 
> gs://fc-dcea072f-393f-4e20-8009-bf06ea594923/staging/
> 
> gs://fc-913d548e-0526-4fde-ae86-c812648e69cd/staging/
> 
> gs://fc-dce015ba-2eed-4fd2-8b66-c88a2ee08f6c/staging/
> 
> gs://fc-42fd83ef-cf64-47c9-aa58-23eefa9496f7/staging/
> 
> @theathor@ucsc.edu We really need a way to expose the metadata graph in a simpler fashion. Both staging areas and TDR itself are too complex to navigate, even for someone more or less familiar with this spec.

The first tasks is to understand the pros and cons of following this approach for contributor matrices, is it a good place to start iterating from or do we need something different

**Comment by clairerye** [comment]
I have started a proposal to evaluate possible options. It needs input on what schema changes we would want, assuming we would like to go down that route - but having a look at the pros/cons of several options seems a good starting place.
https://docs.google.com/document/d/1_L2vvYP9d3T5LBzAICTZbEe-fKfM8AfqX0mxqbeGVqE/edit

**Comment by lauraclarke** [comment]
I had a quick chat with Tony about this after our meeting and I wanted to capture that discussion somewhere before I forget

We were discussing the challenges associated with associated matrix files with projects where we don't yet have the raw data (managed access being the obvious angle, datasets subject to GDPR might also fall into this bucket)

From the perspective of the browser finding the matrix files, finding all analysis processes and getting down files associated with the works. The downside to this is the analysis processes won't contain all the metadata that people will want to know about the contents of a matrix file, particularly the organ, technology and development stage. 

How plausible will it be from a publication and the metadata which is publicly released about an EGA project to create a full experimental design graph which doesn't have any "real" data files associated with it, so we can consistently represent matrices regardless of if we have raw data or not

@aaclan-ebi @mshadbolt your thoughts on this would be appreciated?

**Comment by aaclan-ebi** [comment]
Hi Laura,

> How plausible will it be from a publication and the metadata which is publicly released about an EGA project to create a full experimental design graph which doesn't have any "real" data files associated with it, so we can consistently represent matrices regardless of if we have raw data or not

I have been thinking about this. Currently, we've always been exporting metadata + data with a complete typical graph and the links.json contains all the linking info for an assay.

(might be better to have diagrams, sorry!)

```

donor -> p1 -> specimen -> p2 -> cell_suspension -> p3 -> sequencing_file1 + sequencing_file2
donor -> p4 -> specimen2 -> p5 -> cell_suspension2 -> p6 -> sequencing_file3 +  sequencing_file4
```

The exporter currently requires the full graph for it to export all because we're doing graph crawling per assay. But I'm thinking we could actually change the way we export things or the way we create links.json. 

We can still allow the users to submit even if they can't provide the linking information or all the metadata.
We'll create links.json which will contain all linking info for the whole project

For the experiment graphs above, the links.json will be:

```
donor -> p1 -> specimen

specimen -> p2 -> cell_suspension

cell_suspension -> p3 -> sequencing_file1 + sequencing_file2

donor-> p4 -> specimen2

specimen2 -> p5 -> cell_suspension2

cell_suspension2 -> p6 -> sequencing_file3 + sequencing_file4

```

The submitter can provide however they want to link entities. If there are missing metadata or missing linking info they should still be able to submit it

e.g.
```
# when there is no info on specimen
donor -> p2 -> cell_suspension -> p3 -> sequencing_file1 + sequencing_file2

# when there is no info on donor
 cell_suspension2 -> p6 -> sequencing_file3 + sequencing_file4

```

then links.json will only contain

```
donor -> p2 -> cell_suspension

cell_suspension -> p3 -> sequencing_file1 + sequencing_file2

cell_suspension2 -> p6 -> sequencing_file3 + sequencing_file4

```

to support matrices, the following linking scenarios can be permitted
```

cell_suspension2 -> p1 -> sequencing_file3 +  sequencing_file4 ->  p2 -> matrix_file 

cell_suspension3 -> p4 -> sequencing_file4 ->  p5 -> matrix_file 
cell_suspension3 -> p4 -> sequencing_file5 -> p6 -> matrix_file

cell_suspension -> p7 -> matrix_file1 

```


This will make things flexible for submitters but it may have impact on the downstream components and data consumers. But the way I see it now, the only important thing for the consumers are the files and some related info (which is the metadata but i think they don't care much if those related info is organised or not).


Thanks
Alegria

**Comment by lauraclarke** [comment]
@aaclan-ebi I think inferring a reasonably accurate graph from a publication is plausible, we might not have an entirely accurate graph that reflects how things are archived in the EGA and we might need to make sure there is a reasonable set of expectations on that front but that isn't a technical problem but a documentation problem

**Comment by Wkt8** [comment]
Have created an updated google doc with the current proposal of how to change the metadata schema, in order to capture contributor-generated matrices metadata here: https://docs.google.com/document/d/1AaE0RCXOhvU8bOT2Tf9G3-0M1mKmlqOZRbubyS8uo4o/edit# 

Will send out to different downstream components to get their opinion and feedback.

**Comment by Wkt8** [comment]
Have gotten very useful feedback and going to work it into the doc. Next action is to make changes to the wrangling SOP to reflect this.

**Comment by Wkt8** [comment]
Relevant documents are here: 

Schema evolution doc: https://docs.google.com/document/d/1AaE0RCXOhvU8bOT2Tf9G3-0M1mKmlqOZRbubyS8uo4o/edit#heading=h.twehxdl9eif

Test data generation doc: https://docs.google.com/document/d/1kaGRkKX17W6cp6giwWiftnY9_nDyv3TuP_SF42pnSs4/edit#heading=h.c7qb46mhr8o0

PR for metadata schema changes: https://github.com/HumanCellAtlas/metadata-schema/pull/1371
