### ISSUE TITLE
Add metadata properties to project catalogue

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#139]
Decide on the content for the relevant tags in [https://stable.visual-framework.dev/components/embl-content-meta-properties/](https://stable.visual-framework.dev/components/embl-content-meta-properties/) and add them.

**Comment by mshadbolt** [comment]
tried to have a look at existing ebi pages but seems like a lot don't do this at all
Here's my suggestion as a starting point

Content descriptors
- embl:who AIT, HCA, humancellatlas (?)
- embl:what Human Cell Atlas
- embl:where - i feel like this is not applicable
- embl:active what (?)

Content role:
- embl:utility work based (?) 'if content is task and work based or if is meant to inspire' ?huh???
- embl:reach public

Page information:
- embl:maintainer - either AIT or Tony Burdett
- embl:last-review  - Can this be automatically filled on deployment?
- embl:review-cycle - not really applicable? thought maybe we can choose a random number
- embl:expiry - Not needed

anyways I am just guessing, maybe @gabsie has some insights.

They seem very much aimed more toward content on the main embl site, not really for ebi resources/services...

**Comment by gabsie** [comment]
Hi, I am not sure about the meta tags above for EMBL (but will follow with the VF team to understand more)

What we should do for now, so that the page is better optimised for searches through Google, is add Title and Description which will help with its visibility and search in Google. I have some suggestions below, please feel free to comment. (This is also a good exercise in succinctly explaining to an outsider what this is ;) @tburdett @mshadbolt )

**Title:** and **Meta Description**
Suggestion 1
EMBL-EBI Catalogue of single cell datasets for the Human Cell Atlas
A curated and comprehensive list of single cell data from the Human Cell Atlas community, maintained by EMBL-EBI curators.

Suggestion 2
EMBL-EBI Catalogue of single cell data for the Human Cell Atlas
A curated and comprehensive list of single cell projects from the Human Cell Atlas community, maintained by EMBL-EBI curators.

I have tested these through common tools which aim to get the optimal number of symbols, and it shows how this will appear in Google search results. 

See them as screenshots: ![Screenshot 2021-01-20 at 16.55.03.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/f58694f1-b288-4d26-b469-c4100efc421d)

![Screenshot 2021-01-20 at 16.34.11.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/d4955d15-4757-4eb8-8bdb-e177e1bf873f)

**Comment by tburdett** [comment]
I've no strong opinions on this but let's avoid creating further confusion about datasets/projects/etc. We seem to be fragmenting around project/data/dataset catalogue/index/list. Pick one and stick to it consistently! :)

Re metatags - the ebi:* tags are new to me, but in general the GWAS Catalog does a good job (because I added some of them, obviously)...

```
<meta name="description" content="The NHGRI-EBI GWAS Catalog: a curated collection of all human genome-wide association studies, produced by a collaboration between EMBL-EBI and NHGRI" />
<meta name="keywords" content="GWAS Catalog, GWAS, NHGRI, EBI, EMBL-EBI, SPOT" />
<meta name="author" content="Tony Burdett, Emma Hastings, Dani Welter, SPOT, EMBL-EBI, NHGRI" />

``` 

`embl:where` should be EMBL-EBI and for `embl:maintainer` you can use your own names (assuming you are happy to do so) and AIT as the group. I think you can simply omit anything else you're not sure about for now - this doesn't need to be perfect and it's probably not worth diving too deep with the visual framework folks unless we find things are showing up weirdly in search results.

**Comment by gabsie** [comment]
Hi, 

Meta keywords are no longer registered by Google, so I would then advise to go with:
**Suggestion 2**

Title: EMBL-EBI Catalogue of single cell data for the Human Cell Atlas
Description: A curated and comprehensive list of single cell projects from the Human Cell Atlas community, maintained by EMBL-EBI curators.

Gabs

**Comment by mshadbolt** [comment]
looks good to me. 

I would be hesitant to put peoples' names in the `author`/`maintainer` fields because they inevitably go out of date and don't get updated, Tony's example from the gwas catalog is a pretty good example of that.

**Comment by tburdett** [comment]
Just putting the team here is fine. I always think it is nice to be named and credited for your work, and It is vaguely useful to add names for future developers - if someone else takes over in future they will know who has worked on the code in the past and who to ask. But, of course, there's plenty of other ways to meet that goal. From the "credit" angle, it also doesn't especially matter if they go out of date (unless someone redevelops the page without updating the content!). We're definitely into non-critical decisions here though!

**Comment by gabsie** [comment]
Hey @jacobwindsor - tagging you here.
Let's go for now with this suggestion:
Title: EMBL-EBI Catalogue of single cell data for the Human Cell Atlas
Description: A curated and comprehensive list of single cell projects from the Human Cell Atlas community, maintained by EMBL-EBI curators.
