### ISSUE TITLE
Port Project Catalogue to Angular

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#173]
- [x] create angular app 
- [x] port dev environment, make sure it is installable on another dev's machine
- [x] create components for the different elements
- [x] port build and ci/cd process
- [x] cleanup unnecessary files
- [x] unit tests @jacobwindsor 
- [x] about page (https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/318)
- [x] Incorporate the VF-hero component into the HCA Project Catalogue(https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/307)

See [PR](https://github.com/ebi-ait/projects-index/pull/42)

**Comment by amnonkhen** [comment]
See analysis of different options: https://docs.google.com/document/d/1u2aBsuAaQj-mWHs_h8PU2yHs_ARaKGs7sYmKN9_8-ik/edit

**Comment by amnonkhen** [comment]
@clairerye I don't this this will fit in this sprint, as @jacobwindsor is doing Ops.

**Comment by jacobwindsor** [comment]
Thanks for creating this @amnonkhen.  No it won't fit into this sprint but it is also TBD if/when we'll do this. We are going to release the catalogue this sprint and gather feedback and analysis results. From then on, we'll see if further development is worth while and then port to angular before developing new features

**Comment by clairerye** [comment]
Thanks @amnonkhen, as @jacobwindsor says, we shouldn't be doing this either this sprint or next sprint, until we have tested our assumptions about how useful this is. I think for now, we should remove it from the milestone, and we can add it in if the feedback is positive.

**Comment by yusra-haider** [comment]
https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/318 --> the ticket for adding Eligibility Criteria and Prioritization sections to the About page was also done as part for this ticket. 
Feedback / todo with @gabsie: @gabsie to shorten to text for both sections


https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/307 --> ticket for adding the header to the website  was also done as part of this ticket.
Feedback / todo with @gabsie:
- @yusra-haider make the white box on main page wider (fit the heading in one line), refer to the EBI training site
- @gabsie to shorten the subtitle text
- @gabsie to provide text for the about page header

cc @clairerye @amnonkhen

**Comment by gabsie** [comment]
Hey @yusra-haider 

1. A suggestion for the Homepage Title and subtitle. The Title should be on its own line, without breaking.

HCA Project Catalogue
A comprehensive list of cellular resolution datasets for the Human Cell Atlas. 
About the catalogue  (link to About) (Can we actually move the link to be at the end of the above sentence and not fall on next line? Just asking..)

Comments there:
a) ideally I want the height of the header to be as it appears on the Training page, so that people can see more of the content below. If I need to shorten the above texts more, I will.
b) the feedback button is hidden by the header, this should be fixed.
c) I have to find a way to say Add a project - from somewhere else, and lose that button there, that will be for me for next sprint


2. About page

Title
About the Catalogue
Criteria and selection process for the HCA Project Catalogue

Same comment about the height of the header.

I will additionally provide the edits to the copy.

All the best,
Gabby

**Comment by yusra-haider** [comment]
@ke4 tagging you here as you would be taking up these stylistic improvements.

cc: @gabsie @clairerye @amnonkhen

**Comment by clairerye** [comment]
final testing and deploying @rays22

**Comment by rays22** [comment]
I have compared the functionality of the dev and prod versions. I **could not find any differences in functionality** between the two. I ignored any differences in catalogue content.

Tests:
1. `Search projects` box
    - Query: `bone`
        - **PASS**
    - Query: `mus musculus`
        - **PASS**
    - Query: `Mus musculus`
        - **PASS**
2. `All organs` box
    - Query: `Adrenal gland`
        - **PASS**
3. `All technologies` box 
    - Query: `CITE-seq`
        - **PASS**
4. `All data locations` box
    - Query: `HCA Data Portal`
        - **PASS**
5. Sorting by `Date added`
    - **PASS**
6. `Add a project`
    - **PASS**
