### ISSUE TITLE
add project metadata as a contributor - full details

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#204]
As a data contributor I want to see and fill out the project metadata necessary in order to submit data to the HCA. 

Change the user flow so that contributors can complete all project metadata and then download a spreadsheet. This is an intermediate user journey while we work on what the complete submission process will be for a contributor via the UI.  

Acceptance Criteria

Given a contributor is logged in, and has a new project to add
The contributor can enter all the project metadata in the form
The contributor can submit the form
The contributor can come back and edit the form
Contributor should not be able to upload or submit project to the DCP/archives. These additional functionality (tabs) should be greyed out

Wrangling SOP should be updated as part of testing this user story

This will possibly solve #96 or #96 will need to be solved first.

 Nice to have: Be able to “save” a partially complete project and come back to it later this is story #214

Background info:
Currently the contributor is restricted to adding some project metadata only

**Comment by amnonkhen** [comment]
We can increase session timeout, or save in the db partially complete forms.On Mar 9, 2021 19:58, Claire Rye <notifications@github.com> wrote:
#206 time out could also be relevant here - how do we ensure users don't lose a partially completed form?

**Comment by clairerye** [comment]
testing on dev, this is looking really good! I did notice a few things.

When you first click on the funders tab it is blank and you have to click the + button to add - can it by default show the form to complete (we can assume there will be at least one funder) also funding is not required (except it actually is, when you go back and view the project there is a validation error)

 Accession time frame is asked twice-
![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/e56f9ac1-7665-427b-9eaf-580b72e1bd0d)

Summary text before "registering" needs to be updated to reflect the new flow. @gabsie do you and I want to discuss what this should be?

 Text under the Send tab probably needs more info about how to complete the spreadsheet, but this is a great start.

When I go back and view my project after completing it, I no longer see the additional funders tab. But if I hit the edit button it is there and I can edit it, although I still get the json error. Additionally when I am in the "edit view" I no longer see the tabs across the top, but I do when I am viewing the project.
![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/8adbdd40-6f15-45ff-b8ff-3063da408f05)

![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/61369296-6ab4-45eb-ba6a-8c530082cce2)

**Comment by gabsie** [comment]
hey @jacobwindsor, @clairerye 
I have added a screen to denote this third tab - which instead of send can say Data upload. We discussed with Claire yesterday - and on it we will put instructions for both metadata and data further submission.

Also - in the Project tabs, I have placed one called Save instead of Summary, because that is what the person will be doing..

https://www.figma.com/proto/tMrlll3t2XRScDe5K1SG0P/HCA-Ingest-Sprint-related-designs?node-id=253%3A6&viewport=-543%2C411%2C0.08194863796234131&scaling=min-zoom

Also -  no need to worry about UUID because I learned that until you hit save, nothing gets saved currently? We can address that in further sprints.

Let me know if questions!

Gabs

![Sprint 10 - Project tab - top tabs amendment.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/6bd164d5-822e-44cb-939b-0b6f8a2f6a0f)

**Comment by ami-day** [comment]
Tested this from a wrangler account: it does not cause any problems on the wrangler side. It works really nicely from a wrangler point of view. I will just suggest 1 thing which I think we all know and agree on anyway: the form is still asking us to create each new contributor separately. Can it use the publication author list in the text box in the publication step to auto-fill the contributors list, so that we only need to add the curator as an additional contributor?

**Comment by clairerye** [comment]
Thanks @ami-day! Totally agree and you will be pleased to hear that is coming in #136
