### ISSUE TITLE
Create another Gitlab Runner

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#260]
After #257, integration tests will be running more frequently. We should spin up another runner to run the integration tests so more tests can be run in parallel. We could consider using Kubernetes to do this and move the existing runner over to Kubernetes.

**Comment by jacobwindsor** [comment]
We could also consider using our own runners for build steps. At the moment, we're using the webadmin shared runners

**Comment by jacobwindsor** [comment]
I've started this draft PR for deploying to k8s https://github.com/ebi-ait/ingest-kube-deployment/pull/40

**Comment by ipediez** [comment]
The developers to have a discussion about this, @amnonkhen will set a session

**Comment by jacobwindsor** [comment]
I have removed the tags for integration tests so that they can be run on any available runner

**Comment by amnonkhen** [comment]
@amnonkhen to review PR today. New runner already live and running.

**Comment by jacobwindsor** [comment]
CI jobs should be a LOOOOT faster now:) The new runner had Docker In Docker and the correct permissions to get AWS secrets to run integration tests. So it can run all of the jobs we do in all projects and is available to do so. If you see `running on ingest-eks-dev runner` in the job logs, it's using this :)

This is running in `ingest-eks-dev` cluster but the [PR](https://github.com/ebi-ait/ingest-kube-deployment/pull/40) need reviews and merging still @amnonkhen @aaclan-ebi @prabh-t @MightyAx @yusra-haider 

If it's all working well, you could consider deploying the same to `ingest-eks-staging` so we have more runners available. Note that this will use some resources from staging. To do this:

1. Create a new secret in `ingest/staging/secrets` called `gitlab_group_runner_token` with the same value as the same key in `ingest/dev/secrets
2. Re-deploy secrets on `ingest-eks-staging`
3. Create a `staging.yaml` file in `infra/helm-charts/gitlab-runner/environments/` and update the values accordingly
4. Deploy `gitlab-runner` to staging
5. You should see the new runner appear in the "Runners" section of [this page](https://gitlab.ebi.ac.uk/groups/hca/-/settings/ci_cd)
6. You should now have more runners available!

**Comment by MightyAx** [comment]
https://github.com/ebi-ait/ingest-kube-deployment/pull/40 needs review, probably from @MightyAx and @aaclan-ebi

**Comment by aaclan-ebi** [comment]
Hi @jacobwindsor (I know you're on holiday so please feel free to reply when you're back)

I got some questions regarding this change:

1. ~Do we want to add the GitLab runner deployment in staging and prod too?~ It looks like it's up to us, and you recommended against not deploying this to prod.
2. Will the current GitLab runner deployment in the dev environment run tests from prod, staging, dev tests too? It looks like it actually.

This means that any cluster node should have access to dev, staging and prod secrets which feels strange but it seems that previously we already have a GitLab runner role ( attached to the EC2 instance) which has full secrets and admin permissions which doesn't make it any worse. (It's actually a bit better now because the new policy are more specific) I've modified the [policy](https://console.aws.amazon.com/iam/home#/policies/arn:aws:iam::871979166454:policy/secrets-access-for-integration-tests-runner$jsonEditor) to have access to staging and prod secrets as well.

**Comment by jacobwindsor** [comment]
@aaclan-ebi . Yes it's just a runner and can run integration tests as well as our builds. Now all of our pipelines (except integration) can run on this or use the shared EBI runners. 

Ah I see why it needs the secrets now. We can reasses this if it's a security risk. We can just change the integration tests to use secret values stores in gitlab rather than AWS. That way we can run integration tests on any gitlab runner including the shared EBI ones too. This way was just minimal changes
