### ISSUE TITLE
Project statuses - proposal 

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#279]
As a contributor/data wrangler/stakeholder I want to see the statuses of HCA eligible projects so that I can do my work.

** Acceptance Criteria / Definition of Done **

* Given we establish these statuses per project in the ingest DB
* When any of the user personas above sees the statuses suggested
* Then they know how to understand the project status and continue with their work (submit, wrangle, report)

Tasks:

- [x] Suggest statuses that make sense to the above user personas
- [x] Raise the statuses for feedback with wranglers/stakeholders
- [x] Decide on final list for development implementation

**Comment by gabsie** [comment]
Hi, everyone

As we have recently raised the subject about Data tracking, we are now at a stage to establish appropriate project statuses, so that these are meaningful to data wranglers (first), and also make sense to contributors.

For this piece of work, I have suggested a process of how I see these working, as well as their concrete labels.

In the Miro document I have got the whole story and the statuses, but for easier commenting I have got them [in this doc](https://docs.google.com/document/d/1IjsR69twGSECFicENtXNdTpt86buQ422jLpZHccKLFk/edit#bookmark=id.i189ku14za4z) as well..

@mshadbolt @ESapenaVentura @ami-day @rays22 @aaclan-ebi @clairerye @lauraclarke @tburdett @ofanobilbao  - your comments on the doc above is welcome.

All the best
Gabby

**Comment by mshadbolt** [comment]
thanks @gabsie looks good.

One thing we have struggled with when assigning statuses in a one dimensional way is that a project can be in multiple statuses at once, and this can lead to confusion about where a project is in its lifecycle. I am wondering if we actually need different statuses for each separate action. I kind of see different phases to the wrangling process.

- **Wrangling status**: publication/contributor -> ingest

Then the next steps may happen in parallel or may be disjoint in time
- **DCP status**: ingest -> HCA data browser
    - ready for export
    - exported
    - published
    - stalled
    - won't be exported
- **Archiving status**: ingest -> EBI archives
    - archiving
    - archived (held until release)
    - archived (released) 
    - stalled
    - won't be archived
- **SCEA status**: ingest -> SCEA
    - converting
    - staged in gitlab
    - reviewed
    - published in SCEA (how do we know when this happens)
    - stalled
    - won't be brokered

I think you have kind of hinted at that, but maybe having separate statuses for each of the three paths might make things less confusing. That is, visualising it as a branching tree rather than a linear path.

**Comment by ofanobilbao** [comment]
Thanks Gabs,

It looks quite good to me.

I left a couple of comments, but I totally agree with Marion. For me when trying to fill the reporting for year 4 for instance, it was many times very difficult to establish what we had done with the different datasets because of this one dimensional status.

I believe what Marion suggests here makes total sense. If we could describe statuses for each separate action I believe it would be best for anyone. As Marion hints in one of her comments, a dataset might have not been exported to DCP yet, and is archived and gets accessions. The export to SCEA might also happen either before or after. 

Thanks for sharing

Oihane

**Comment by clairerye** [comment]
Thanks @gabsie Looks good. I agree with the above from Marion and Oihane.

**Comment by tburdett** [comment]
Hi @gabsie. I did a review, I didn't comment on the doc cos it all looks totally sensible to me. Couple of very general points:

1. A data flow diagram might help to visualise this. I really like the "branching tree" suggestion from @mshadbolt - we have used a tubemap style visualisation of this in the past. Understanding where the data "stops" and transitions are makes it easy to see if there's something important missing
2. I think there's an overlap between project statuses and submissions states, such as from the original [ingest service spec doc](https://docs.google.com/document/d/1MDzoO4WkMgLgmRvROnirf3KEzvwDhSzlI-QwZ3eIjac/edit#heading=h.msshc3lqlfcz). They're definitely not **the same** but a cross-walk might help join technical/system operator needs with user needs, maybe?

Both comments aren't critical to moving forward, just possible suggestions that might help visualise future improvements. Nice job with this!

**Comment by clairerye** [comment]
I have an updated tube map visualisation in progress, I will finish it asap... its got a bit more complicated than it was.
https://docs.google.com/drawings/d/1UqUH2llMs5iBPifTljecZoW9lbtP79dKs24x6qiDfYQ/edit

**Comment by gabsie** [comment]
Hi,

I am going to close this ticket and open up a new one for the implementation, last task for this list.
But as a resolution, suggested statuses as per board and discussions with wranglers are:

![Screenshot 2021-05-18 at 15.51.51.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/3ba05ac0-1cdd-4a7a-a3e0-fc7c41634094)

I will as a start suggest the Wrangler -driven statuses to become available in backoffice and correspond to the statuses in the data tracking sheet.

Gabs
