### ISSUE TITLE
suggest a project

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#360]
see https://docs.google.com/document/d/1fSIPU85oDj_Ee09zyyHegHJwwy66vN-cGgn12hJC1B4/edit

**Comment by clairerye** [comment]
Form that alerts wranglers in some way when the form has completed and its contents so a wrangler can review it
contains:
Name
contact email address 
DOI/URL
Optional Free text for additional comments

**Comment by clairerye** [comment]
possible dependency in #313

**Comment by MightyAx** [comment]
Implementation Idea:
Unsecured Post/Get endpoint on ingest-core that puts the project in the database but not in the catalogue with a wrangler status that allows them to find it.

new project with just:

- a doi
- a corresponding contributor
- wranglingStatus: New
- inTheCatalogue: False

Something we discussed was using the uniqueness check on doi to reject doi's those already exist in ingest, with nice error messages, for example:

- "That publication is already being considered"
- "That publication has been marked ineligible"
- "That publication has already been added to the catalogue"

If this implementation path is chosen we need to also add in #313 (or a dedicated page for listing New projects) so that the wranglers can triage and assign new projects suggested from the catalogue so that they can be reviewed for Eligibility.

**Comment by clairerye** [comment]
If we are collecting the persons name and email could we also add that into the notes section on the admin page? (this is a nice to have! not essential so happy for it to be out of scope for now.)

**Comment by clairerye** [comment]
need to consider GDPR and terms and conditions for this

**Comment by gabsie** [comment]
Hi, @jacobwindsor and @MightyAx 

Attached the suggested form for suggesting a project, I am only now doing the Thank you page, and will upload it here as well.
Please ask me questions. (Updated the file, after Claire's comment)

![Suggest a project.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/1ff7d882-7f49-4445-b025-db9682d28890)


https://www.figma.com/proto/Ajxve72idcWGOB07GKy8pC/HCA-ingest-Master?page-id=0%3A15981&node-id=597%3A12&viewport=-13392%2C-2338%2C0.30283689498901367&scaling=min-zoom


Gabs

**Comment by clairerye** [comment]
Can we have a tick box terms and conditions please - link is: https://www.ebi.ac.uk/data-protection/privacy-notice/human-cell-atlas-ingest-submission
maybe just above the send button? @gabsie

**Comment by gabsie** [comment]
Yes, just updated the image! Sorry
And here is the Thank you page as well.![Suggest a project-thanks.png]![Suggest a project-thanks.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/675a19d5-c35a-43a5-a32e-da80c683dc5e)

**Comment by clairerye** [comment]
They look awesome, thank you!

**Comment by MightyAx** [comment]
Ah, I don't think I understood what a Project URL is and why it's a good substitute for Publication DOI.
Is this so we can take pre-publication info?

**Comment by clairerye** [comment]
I wanted to make it more flexible than simply a publication DOI, so people could use archive URLs, bioarchive URLs (which mostly but not always have a doi) their own website like the covid19 portal etc- lots of which was pre publication. Sounds like we need to change the wording or we perhaps need some examples after it to make that more obvious?

**Comment by MightyAx** [comment]
I think it just means we can't automatically put it through the DOI Enrichment routine we use for the UI / Script Loading. But perhaps that wasn't ever a requirement.

**Comment by gabsie** [comment]
hey @jacobwindsor 

I entered my details but it deosn't allow me to submit, while on the surface everything should be correct (using a real DOI![Screenshot 2021-06-25 at 16.31.02.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/62f14b6e-02c0-46be-8c4c-7cc127b7c48f))

**Comment by gabsie** [comment]
changed my email to not be all caps
worked.
but the all caps one was from my remembered info
