### ISSUE TITLE
low scores in app browser performance tests

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#383]
App scores low in performance, accessibility and best practices.
Also, page is blocked from indexing.

![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/1a8d3b03-6feb-4322-84ea-a8cedef618fa)

**Comment by jacobwindsor** [comment]
I actually get different results for this when running against prod.

![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/37db3c71-a963-454c-95d9-8d47fe4f054e)

I think in general we score pretty well for an angular app. It's hard to make the first contentful paint shorter when we're serving from an API. Anyway, here's a list of TODOs:

- [x] Increase cache TTL for static assets (runtime.js, polyfills.js, webfonts, VF stylesheets and JS)
- [x] Use latest angular which has no security vulnerabilities
- [ ] Get this on Google (see below paragraph)

We also don't need a robots.txt file ([see here](https://developers.google.com/search/docs/advanced/robots/robots-faq)). The reason we are not on Google is **most likely** because we are a subpage of the EBI website but there is no links on the EBI website root (ebi.ac.uk) to the project catalogue. We will need to be in the main EBI robots.txt file or be linked to somewhere so that Google can reach us when it crawls the EBI site. We can [submit a sitemap](https://support.google.com/webmasters/answer/156184) or add a link somewhere (or in a few places) in the EBI website and ask [Google to re-index](https://search.google.com/search-console/welcome?action=inspect&utm_medium=referral&utm_campaign=9012289). The latter is probably better  @clairerye @amnonkhen How can we get links on the main EBI site?

**Comment by tburdett** [comment]
For search engine performance, before we embark on a complex process to update the EBI corporate site (and assuming we haven't already done this) I'd try registering the project catalogue with search.google.com. in conjunction with good keywords this has usually proved enough to give good results on other services (e.g. Biosamples)

**Comment by jacobwindsor** [comment]
The catalogue has now been verified by Google. It should crawl it in a day or two

**Comment by tburdett** [comment]
Very nice. Let's see if that gives us good enough results before we go much further with the EBI corporate site

**Comment by clairerye** [comment]
Search phrases could include:
hca/human cell atlas and data/dataset/project/publications/catalogue/index
human single cell sequencing and data/dataset/project/publications/catalogue/index

not sure if anyone has any other thoughts?? @gabsie?

**Comment by jacobwindsor** [comment]
[Here](https://search.google.com/u/1/search-console?resource_id=https%3A%2F%2Fwww.ebi.ac.uk%2Fhumancellatlas%2Fproject-catalogue%2F) is the google dashboard for the crawling status

**Comment by tburdett** [comment]
Hey @jacobwindsor , I'd be interested in having a nosey around this dashboard but I don't have access. What's the sharing policy for this, do I need to be added to a team somewhere or can you just grant me permissions?

**Comment by jacobwindsor** [comment]
I have added you (@tburdett), @gabsie, and @clairerye. If anyone else would like permissions please just ping me.

I thought anyone would be able to see it since it's not confidential I think.
