### ISSUE TITLE
fix failing integration test on gitlab

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#412]

**Comment by jacobwindsor** [comment]
This is fixed. I have also increased the number of available runners to 2 by utilising the gitlab runner running with docker.

However, I have found the ingest-kube-deployment-gitlab-runner EC2 instance and am not sure what it is. I cannot get access to it since I cannot find the SSH key. I think we could use this as another runner, increasing our available runners even more so and making our tests more parralelized
