### ISSUE TITLE
Introduce a field for HCA publication in the project form, and link to the metadata schema

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#424]
As a data wrangler I want to be able to select whether a project is a HCA publication or not, so that we can prioritise these projects better, visualise that information in the DCP ingest backoffice and the HCA DCP browser.

** Acceptance Criteria / Definition of Done **

* Given I am entering details about a project
* When I see a field for HCA publication, I wish to select whether it is or not, so that
* Then this information will be saved in ingest, as well as link to metadata and visualise eventually in the DCP browser.

- [ ] UI design

- [x] Linking to the metadata schema

- [x] Front Dev implementation

**Comment by Wkt8** [comment]
official_hca_publication is a required field, that at the moment we cannot change in the UI. 
This means that for some projects and submissions, we cannot export them because we have no way of adding the official_hca_publication information (we cannot update project data by updates). 
So we want the ability to - in the project.publications tab of ingest UI - to change / select whether the project is an official_hca_publication.

**Comment by amnonkhen** [comment]
assigning to @aaclan-ebi  because @jacobwindsor is on Ops

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/118

**Comment by jacobwindsor** [comment]
Testing steps:

- Create a project
- Add three contributors:
  - For the first one, tick corrresponding contributor
  - for the second, tick and then untick corresponding contributor
  - for the third, never touch the corresponding contributor box
- Add three publications:
  - For the first one, tick the HCA official publication box
  - For the second one, tick the HCA official publication box and then untick it
  - For the third, never touch the HCA official publication box
- Check the project metadata for the project
  - Corresponding contributors should be: true, false, and not existing for each contributor, in that order
  - HCA publications should be: true, false, and false for each publication, in that order

**Comment by ami-day** [comment]
Hi @jacobwindsor this seems to be working fine based on the above testing steps, see: https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=f59fd331-b73c-47a8-b1f7-daeb44a3e642&tab=project The only thing I would point out is that rather than the corresponding contributor or publication status being shown as false, or no, the field name is not shown at all in the cases where the tick box was not selected.

**Comment by jacobwindsor** [comment]
Thanks @ami-day That is the desired behaviour

**Comment by ofanobilbao** [comment]
@jacobwindsor when I am editing a Project in the UI and I want to reflect is not a HCA publication, I keep the HCA box unticked (I have also tried ticking and unticking). When I click save, I get JSON error saying that "Should have required property 'official_hca_publication' at .publications[0]. Should I file that as a Bug?
