### ISSUE TITLE
integration test stuck for an hour

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#434]
See in https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/551587

From the log:

It shows this message
```
0:00:12 WAIT FOR VALIDATION...
```

then repeats the following for an hour until failure:

```
0:00:12 envelope status is Pending
0:00:12   _envelope_is_in_state returned False
```

**Comment by ESapenaVentura** [comment]
@aaclan-ebi and @ke4 investigated this. 

Issue is:
- Dev branch --> schema dev
- Schema update pushed a required field that was not reflected in the integration test spreadsheet

Outcomes:
- Integration test spreadsheet updated for now
- Decided to go for integration test from spreadsheet in schema-test-data (Always updated). That will be done later, for now using schema repo.

**Comment by aaclan-ebi** [comment]
Notes:

1. dev integration test - it couldn’t download the test spreadsheet from the metadata-schema repo’s develop branch anymore. The tests download from the link: https://raw.githubusercontent.com/HumanCellAtlas/metadata-schema/develop/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx

Fix: point the test to staging branch and redeployed ingest-core in dev to point to staging schema env/url ([commit](https://github.com/ebi-ait/ingest-kube-deployment/commit/602e75e1f243fe5e6d504da72e3c4dab4212f18b) on config changes)

2. staging and prod integration test - both are failing the project metadata validation should have required property 'official_hca_publication' at .publications[0] 

Fix: updated the test spreadsheet in metadata-schema staging and prod branch so that the test project metadata in the spreadsheet will have `official_hca_publication` property

A new ticket was created to further improve the integration test to use the official test data from schema-test-data repository https://github.com/ebi-ait/dcp-ingest-central/issues/436
