### ISSUE TITLE
UX design for the filters in backoffice (for ticket 426 )

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#450]
Uploading this as a start, and for comments
![Projects - Filter Wrangler list - expanded.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/7a31377f-81cf-4489-b089-7c748b24abbb)

**Comment by Wkt8** [comment]
@Wkt8 @ofanobilbao to have a look and comment

**Comment by Wkt8** [comment]
From a UI perspective:
Questions: 
- Do you have a screenshot of what it looks like after clicking on 'close filters'?
- Maybe have a 'search' button, so that it only searches after you have set your separate search terms in each category? 
- Is there any specific reason the 'Species' isn't on the same row as the 'HCA publication' and 'Cell count'? 
- We will have to be picky about what columns we show in the results. We can't show the columns for each of the categories or it'll be way too crowded! Perhaps default to a small number of them, with options to show more? 

Comments: 
- Cell count would probably need to be a range of some sort... But that isn't a UI comment! 
- Additionally: I don't think the 'Type of Data' field exists. 

Likes!! 
- I like the way the colors change when you have set a specific filter in 🙂

**Comment by ESapenaVentura** [comment]
To second 2 of Wei's comments:
- Cell count probably needs a range, with an `N/A` min and a `No upper limit` max
- I think your idea For `type of data` is nice, but maybe instead "Published data? yes/no". @Wkt8 is right in that we don't have that field in the metadata (Or in the project registration form), but I think it can be inferred by the presence/absence of accessions

And to contradict another:
> Maybe have a 'search' button, so that it only searches after you have set your separate search terms in each category?

I have to say that, unless it causes a lot of lag (Which may be the case), having the search update every time you change the filter is something I like. So I guess this may be more of like a person by person kind of thing?


Other than that, I think @Wkt8 summarised pretty well everything I could think of

**Comment by ofanobilbao** [comment]
Sorry for delay on commenting here:

We probably need to be able to filter based on our prioritisation criteria right?

1. Contributor involved? We have the information on the DST as Yes or No. We could translate Yes into Direct Contribution / and No into Publication? Is that even possible?
2. Month and year of publication? Otherwise we will need to go and check the dates on the publications one by one to prioritise. That’s probably a waste of time?
3. Sample type: Primary, Cell line, Organoids
4. Donor locations: I don’t even know how we can prioritise by this at the minute. Is there any easy way to extract this? Should we extrapolate from the publication corresponding author’s location?
5. Organ. How can we extract organ coverage from DCP portal easily? I think this should kind of be related. Otherwise filtered organ coverage from catalogue, only counting projects already in the DCP.
6. Cell Count 
7. Commonality of technology. Recognised single cell technology
8. HCA publication?
9. Data available?
10. Pre-print or paper available?
11. Health_Status: Healthy, or both

Probably you want to be able to filter by all of those. But then once filter applied you don’t necessarily need to see all the fields.

Another possibility I see is as follows, first you may want to add priority 1-3. Or deem something non elegible. To reach that conclusion you might want to see some filters.

And on a second step you might want to take all Priority 1, and add further filtering to prioritise the next X from that list.
