### ISSUE TITLE
Ingest UI hangs when unexpected DOI

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#509]
**Describe the bug**
When registering a project, ingest hangs out without giving any error if the format of the DOI is not the proper one (e.g. URL version)

**Expected behaviour**
- Ingest should throw an error message if the format is not the expected one
- Ingest should not just hang
- (Optional, more feature than bug) helping text would be useful in this scenario to figure out the format

**Comment by gabsie** [comment]
So when I enter this DOI URL:
https://doi.org/10.1038/s41467-021-26902-8
system hangs. Is this the same problem?

10.1038/s41467-021-26902-8 should also give the right warning
so let's get this right. 

Let's investigate

**Comment by gabsie** [comment]
This now works, and maybe was a temporary issue. Might just need an amendment to the hlp text to say this expects the DOI number, not an URL?

**Comment by ofanobilbao** [comment]
The issue also happens repeatedly with the following:

DOI: 10.1111/j.1399-0004.2009.01188.x

https://onlinelibrary.wiley.com/doi/10.1111/j.1399-0004.2009.01188.x 

See screenshots below. The Project is not created. And no error message or advice is given. It just stays blank

![Screenshot 2022-01-10 at 15.46.35.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/25531bb0-cb22-4f37-a743-edfdaf85bfaa)

![Screenshot 2022-01-10 at 15.46.44.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/d2bd75c6-434d-4ceb-8113-a474b3f7b43f)

**Comment by MightyAx** [comment]
1. Use Europe PMC to check DOI Exists
![Screenshot](https://user-images.githubusercontent.com/13031259/150173412-b444ce50-5a18-4ebe-a98f-baab76a170d8.png)

2. When Europe PMC doesn't provide all the properties we now use what we can rather than crashing.
![Screen Recording](https://user-images.githubusercontent.com/13031259/150173862-2a11f363-a27a-41fb-8b21-9e6bf8423d14.mov)

**Comment by idazucchi** [comment]
@MightyAx will continue to work in this, then @ofanobilbao and @gabsie will to some checks

**Comment by MightyAx** [comment]
Added functionality based PR feedback
1. **If the DOI does not exist the wrangler email link includes the searched for DOI**
    - ![Screenshot 2022-01-20 at 14 02 43](https://user-images.githubusercontent.com/13031259/150353836-d7847304-e32f-4085-8f3f-a15f94aadc2e.png)
2. **If the DOI is already used in a project (or more), a link to the project(s) is given in the error message:**
    - ![Screenshot 2022-01-20 at 14 03 33](https://user-images.githubusercontent.com/13031259/150353977-f9489740-78c2-4e5e-8c64-4f604dba5064.png)
    - ![Screenshot 2022-01-20 at 14 03 59](https://user-images.githubusercontent.com/13031259/150353993-1f1a556b-0155-4031-ac13-c7288d706c3f.png)

**Comment by jacobwindsor** [comment]
This is now in staging for testing @ofanobilbao @gabsie

**Comment by ofanobilbao** [comment]
Thanks @jacobwindsor and @MightyAx 

Tests below: 

Test 1: I have tested the DOI that was being stuck for me before. Now it creates the entry in Ingest despite EuropePMC not containing all the fields. This is the expected behaviour right? Or should we pop a message saying that we have populated as much as we could? Otherwise there is no difference with "perfect match" with Europe PMC right?

Test 2: I try the same DOI again once I have saved the previous one. Before it used to tell me already that the DOI had already been used. But I like the improvement of telling me exactly which project is using that DOI and the link to it. I guess it was out of scope but is a nice addition.

Test 3: I have tried some completely random different DOI and they all create entries. They might have also before so I don't think is a useful test.

Test 4: I have introduced the url that Gabs used before and got Ingest UI stuck (https://doi.org/10.1038/s41467-021-26902-8). And I get the screen where it points me to the wranglers saying it was not found on EuropePMC. I don't really fully understand this implementation. The wranglers are the only current users of the system. So referring/emailing them, doesn't make too much sense to me as they are the ones using it. Also if you remove the https:// part of the DOI it works (I haven't saved it so that it can be used for testing future iterations). So I think it is more of a format issue rather than not finding it in Europe PMC. Shouldn't we flag that is not the right format in the first place? I think it would be extremely helpful if when I introduce a DOI that is not on the right format:
- We pop up an error message saying that the format does not look right. And asking to look at the format and amend, and try again.
- Only when the format is right we do search Europe PMC.

Is that feasible? Sorry for the long message

**Comment by jacobwindsor** [comment]
@ofanobilbao I think [this PR](https://github.com/ebi-ait/ingest-ui/pull/154) addresses your issues in Test 4 and also adds a loading state which should make the "hanging" effect less tedious. See images in the PR description

About test 1 - is there any actions?

**Comment by ofanobilbao** [comment]
Thanks @jacobwindsor! Looking at the PR images, it looks as if this should sort that out. About test 1, I would just ignore it for the time being. Looking at my comment retrospectively that would probably just be an enhancement (if anything) if we open up the system beyond wranglers.

**Comment by ipediez** [comment]
@MightyAx to check the PR and review it

**Comment by MightyAx** [comment]
already done

**Comment by MightyAx** [comment]
still waiting for dev's to review https://github.com/ebi-ait/ingest-ui/pull/154

**Comment by MightyAx** [comment]
releasing to staging

**Comment by MightyAx** [comment]
Pending testing by @gabsie / @ofanobilbao before being released to production.

**Comment by ofanobilbao** [comment]
Tests:

1. When I introduce a complete URL rather than the DOI, as expected, an error message appears telling me what the right format should look like, and showcasing a possible format for my specific example. When I correct it to match the format, it creates the project populating with whatever is found in EuropePMC (not saved it for future testing). Looks great to me.

2. When I try to enter a new project using an existing DOI that has duplications in the system, as expected I get a message saying that the DOI is already in use and referencing and linking to the Projects that contain it. I think it is ok. In future improvements I would probably give the message once and link all the associated projects below. Rather than multiple messages, each with one link, if it makes sense. But I think it's fine for now. This could go into an improvement ticket in the future if needed.

3. I have tried registering a new project with a DOI that I believe did not exist (I changed the end of an existing one and searched without any results). As expected (as that was the chosen implementation) it refers you to the wranglers for support. I guess it's ok for now. But I think probably a message saying that it could not find the DOI and maybe to check if it is the right one would be best. The wranglers are the ones using this. And if a DOI does not exist, I don't see what the wranglers could do about it. 

Overall looks great!
