### ISSUE TITLE
Submit ENA study XML to ENA archive

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#524]
After we converted the HCA project to an ENA study XML we need to send it to ENA to be able to store it in that archive.
To be able to send an ENA study XML or any other ENA object(s), we also need an accompanying submission XML in a separate file. We need to name this file to `submission.xml`.

Here is the documentation from ENA how to do it: https://ena-docs.readthedocs.io/en/latest/submit/study/programmatic.html

**Comment by prabh-t** [comment]
instead of specifying the actions in a submission xml and using the `-F "SUBMISSION=@submission.xml"` option, you can use `-F "ACTION=ADD"` directly when adding content. save you constructing an additional xml. for e.g.

`curl -u username:password -F "ACTION=ADD" -F "PROJECT=@project.xml" "https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/"`

If you need to specific a hold date, then I think you can't use the action option like this.

**Comment by aaclan-ebi** [comment]
@ke4 started the work this morning, may not be ready for demo today.

**Comment by ESapenaVentura** [comment]
@ke4 to continue working on this when capacity allows (Dev on ops)

**Comment by ke4** [comment]
@prabh-t I just saw your comment now. We are exactly doing that you are suggesting. The original description was just a suggestion as I read ENA's programmatic submission documentation.

**Comment by ke4** [comment]
I have to populate the ENA related secrets
