### ISSUE TITLE
Ingest - my projects tab is unavailable

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#537]
**Describe the bug**
The tab My projects doesn't load correctly and brings up an unavailable service error message

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://contribute.data.humancellatlas.org/home
2. Log in as a wrangler
3. Click MY PROJECTS tab
4. Wait - sometimes it gets stuck in loading
5. See error

**Expected behaviour**
The page should display the projects assigned to the wrangler logged in

**Screenshots / Logs**
![Screenshot 2021-11-09 at 10.57.55.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/81ccd341-133b-4c2b-a619-253b900034db)
![Screenshot 2021-11-09 at 10.47.37.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/5cd68246-1e3d-4bcd-8546-07fb42fdc341)

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by gabsie** [comment]
hey @amnonkhen - can we get somebody to take a look at this?

**Comment by jacobwindsor** [comment]
I can't reproduce this

**Comment by gabsie** [comment]
@idazucchi - can you tell us if this continues?

**Comment by idazucchi** [comment]
Yes, the issue is still present

**Comment by jacobwindsor** [comment]
@idazucchi can you give me a demo of this sometime?

**Comment by idazucchi** [comment]
@jacobwindsor sure, some time next week?

**Comment by jacobwindsor** [comment]
This appears to only be occurring for @idazucchi 

The issue is only present in the API response from `https://api.ingest.archive.data.humancellatlas.org/user/projects?page=0&size=20&sort=updateDate,desc` which gives a `200 parseerror` status code.

It appears that something is going wrong with retrieving projects that Ida is the user or primaryWrangler of. The project `2ad191cd-bd7a-409b-9bd1-e72b5e4cce81` is duplicated 680 times in the response. I have checked the DB and there appears to be no issues.

Some helpful things:

- Idas user ID: `615ed1eac5d9bc4f29f55ca7`
- `db.project.count({"user": "615ed1eac5d9bc4f29f55ca7"})` = 0
- `db.project.count({"primaryWrangler": "615ed1eac5d9bc4f29f55ca7"})` = 4

**Comment by jacobwindsor** [comment]
This is caused by a circular dependency error: `file` -> `project` -> `supplementary files` -> `file` -> `project` -> ...

I'm not sure why this error is happening. Both `File` and `Project` are using lazy DBRefs so it should be fine. This only happens when you access the project through Ida's my project page and not when you access the project directly. So there must be something specific to Ida's My projects page that is causing traversal of the tree

**Comment by amnonkhen** [comment]
As I understand, the error appears:
- on Ida's "my projects" page 
- for a project she has not created 
- for a project where she is the primary wrangler.

I suggest checking the following scenarios:

1. Change Ida's project's primary wrangler to Jacob
2. load same spreadsheet as a new project with Ida as creator and primary wrangler
3. load same spreadsheet as a new project with Jacob as as creator and primary wrangler
4. load same spreadsheet as a new project with Ida as as creator and Jacob as primary wrangler
5. load a different spreadsheet as a new project with same creator as Ida's project and Ida as a primary wrangler

For all scenarios, the primary wrangler's "my projects" page should be checked.

**Comment by ipediez** [comment]
@jacobwindsor to look into this, the problem only arises when the current user is also the primary wrangler

**Comment by jacobwindsor** [comment]
The above steps listed by @amnonkhen still need looking into. Apologies, I did not end up having enough time last week

**Comment by jacobwindsor** [comment]
I have investigated this again this afternoon and can find nothing specific about this project that causes the issue. I am going to move on for now and see if I have time this sprint to come back to it.

I have unblocked Idas My Projects page by unassigning her from this project
