### ISSUE TITLE
Ability to overwrite existing project info with the project tabs from a spreadsheet

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#549]
As a data wrangler, I wish to be able to find a project I'm assigned to, and upload a spreadsheet for it which contains the full info for the Project tabs, Contributors and Funders. 
(At the moment, if a Project exists, these tabs would be ignored)

- [x] add acceptance criteria - @aaclan-ebi 
- [ ] update user docs

**Acceptance Criteria:**

- [x] 1. **Given** a project and a spreadsheet with project worksheet/s, **when** the user selected the option to update the project and uploaded the spreadsheet, **then** the project is updated and the new entities are created in a new submission.
- [x] 2. **Given** a project and a spreadsheet without a project worksheet/s,  **when** the selected the option to update the project and uploaded the spreadsheet,  **then** an error is reported to the user.
- [x] 3. **Given** a project and a spreadsheet with project worksheet/s, **when** the user didn't select the option to update the project and uploaded the spreadsheet, **then** the project is not updated and the new entities are created in a new submission. 
- [x] 4. **Given** a project and a spreadsheet without project worksheet/s, **when** the user didn't select the option to update the project and uploaded the spreadsheet, **then** the project is not updated and the new entities are created in a new submission.

**Comment by gabsie** [comment]
Design discussion to come up with specific ways of implementation.

**Comment by gabsie** [comment]
Investigate chances of duplication when a new submission gets created and has the same DOI as an already existing project.

**Comment by prabh-t** [comment]
@aaclan-ebi to work on this again tomorrrow.

**Comment by ipediez** [comment]
Changes ready for review (core and UI), finalizing other changes. @aaclan-ebi to ask someone as a reviewer

**Comment by MightyAx** [comment]
2 of (@MightyAx @amnonkhen @ke4) to review PRs

**Comment by aaclan-ebi** [comment]
@gabsie here's the screenshot of the changes in the UI. Let me know if you have some comments/suggestions. Thanks!

![Screenshot 2022-01-04 at 11.07.51.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/1a4da730-fffe-4d65-ab2e-27c7bc3fdb0b)

**Comment by gabsie** [comment]
Perfect - get it up:)
Gabs

**Comment by aaclan-ebi** [comment]
The changes are now deployed to _dev_ and _staging_.

@gabsie found a bug when uploading a spreadsheet with no project worksheet

**Steps to replicate:**
1. Create a project
2. Go to project's details page
3. Select _Data Upload_ tab
4. Click _Submit to Project_ button
5. Upload a spreadsheet without any project worksheets

**Actual Behavior:**

A submission in Pending state is created.  A vague error is being reported to the user. The submission is not linked to the project. When you go back to the project's _Data Upload_ tab, the submission is not shown there.

![Screenshot 2022-01-04 at 17.56.07.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/3762f425-338d-4b38-8be8-76721ddbc13c)

**Expected Behaviour:**

Display a proper error message to the user.

**Comment by gabsie** [comment]
Needs reviews by other devs: @MightyAx @ke4

**Comment by aaclan-ebi** [comment]
@gabsie here's the error message being displayed when the user has specified to update the project but hasn't included any project worksheets in the spreadsheet.

![Screenshot 2022-01-06 at 11.37.56.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/d75d3a90-95ec-4960-aa41-6b43d47719f2)

The submission with that error should also be linked to the project:

![Screenshot 2022-01-06 at 11.35.31.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/9362ab73-0b17-4afc-8c60-43620c8cfd66)

To proceed, the user must delete that submission and try to upload a spreadsheet again.

I've updated the acceptance criteria to reflect that test case and added more test cases, please review.

**Comment by aaclan-ebi** [comment]
The latest changes are now deployed in staging and ready for testing :)

**Comment by ofanobilbao** [comment]
@gabsie and @ofanobilbao to test this

**Comment by aaclan-ebi** [comment]
You could download a sample spreadsheet from https://github.com/HumanCellAtlas/metadata-schema/blob/master/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx

**Comment by ipediez** [comment]
Alegria fixed the issues and it is ready for testing

**Comment by ofanobilbao** [comment]
I just tested all scenarios in the acceptance criteria.

They all worked fine except for:

In scenario number 1, my project in Ingest contained accessions. In the spreadsheet I uploaded I had removed the accessions apart from making some other very obvious changes. After uploading the SPS and clicking the option to update Project Information, everything was updated except that the accessions were kept even if I removed them in the SPS I then uploaded.

**Comment by ofanobilbao** [comment]
When I try removing any other fields on the Project sheets, they get removed fine. I've tried removing one author, the DOI, the publication url. All fine. It's when I try removing the accessions that it doesn't work

**Comment by aaclan-ebi** [comment]
Thanks @ofanobilbao ! I believe this issue on updates is related to ebi-ait/dcp-ingest-central#437 which is an existing bug.

I investigated that issue further it seems that it's affecting only the fields that are located in the root of the metadata json e.g. donor_organism.is_living, age, project accessions 

https://schema.humancellatlas.org/type/project/15.0.0/project
https://schema.humancellatlas.org/type/biomaterial/15.5.0/donor_organism

@gabsie Is it okay if we promote the changes here to prod and I'll try to work on the fix on that ticket? That issue is a known bug in the updates and is affecting all other entities. It might be better to work on it separately so that we can do more testing on the updates, instead of making it part of this story.

**Comment by aaclan-ebi** [comment]
@gabsie I'll wait for the result of your testing in staging as well, in case you find any blocker issues for this story.

**Comment by aaclan-ebi** [comment]
Agreed with @gabsie on slack dm to promote this to prod. This is now in prod.
