### ISSUE TITLE
Project catalogue using contributor information to fill out author list

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#575]
**Describe the bug**
The current implementation of the catalogue uses the contributor information, instead of the author list, to show the publications' authors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to project catalogue webpage
2. Look down until you find "Parisa N" as a contributor

**Expected behaviour**
The list should contain the contributor information from the list of authors of the paper

**Environment**
- [x] prod
- [x] staging
- [x] dev

**Comment by jacobwindsor** [comment]
PR https://github.com/ebi-ait/projects-index/pull/79

**Comment by ke4** [comment]
@MightyAx is going to work on this today.

**Comment by MightyAx** [comment]
@gabsie please test this on [Dev](https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/).

**Comment by gabsie** [comment]
hey @jacobwindsor - I entered projects in backoffice both on dev and staging, just to make sure, but I cannot see those projects on https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/. Is that where I should expect to see this working?

**Comment by jacobwindsor** [comment]
I have fixed the above issue and you can see the test projects @gabsie created here https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/

**Comment by MightyAx** [comment]
@gabs to test on dev

**Comment by gabsie** [comment]
Hey - so I tested this, however because of the functionality which was introduced to not make projects active  in catalogue by default, I cannot see this
I need to discuss with @MightyAx  :)

**Comment by MightyAx** [comment]
@gabs to test [project catalogue on dev](https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/) by entering data with [ingest ui on staging](https://staging.contribute.data.humancellatlas.org)

**Comment by gabsie** [comment]
So I am not sure this is OK still, because even though I added a publication, it now shows publication missing.. Is it that it only picks it up if it's done through the DOI lookup?

**Comment by ofanobilbao** [comment]
@gabsie and @ofanobilbao to catch-up on the testing and wait for Jacob or Alexie to be back

**Comment by gabsie** [comment]
So @jacobwindsor and @MightyAx -  we did 3 test scenarios:
1 test
1. On staging, I create a new project, but instead of going to the DOI entry route, I do it manually, however I still enter a real publication URL. 
2. The catalogue on wwwdev shows the project, however it says preprint or publication citation missing, and it doesn't pick up the one author I added manually.
The project is: test author gabby staging


2nd test

1. Oihane went the DOI project entry route
2. manually went and edited the Contributors to only have her name, and left all the original Authors in the Publications tab
3. The Catalogue also just shows 'citation missing'

3rd test:
1. Complete DOI route
2. didn't change anything, even filled out all information to be valid
3. Catalogue still saying citation missing. 

So for all these tests, we think the publication should definitely show, and it should pick up the authors.
Thoughts?

Gabs and Oihane

**Comment by jacobwindsor** [comment]
@gabsie as discussed before, the catalogue needs a DOI because of the presence of the journal title. The journal title is picked up from looking up the publication. This was part of your original design and you didn't want the user to have to enter journal title.

Also, the script that picks up the journal information from the DOI runs every night so you will see pre-publication or citation missing until that script is ran

I am not sure what has happened with the projects you added right now. Are you sure you gave it a valid DOI? Or maybe that script that grabs the journal title is no longer running on staging. Hard to test without my laptop

I should note as well that, as specified in the ticket, this PR makes the catalogue so it uses contributors from the publication, not contributors listed in ingest. So changing contributors in ingest will have no effect.

**Comment by jacobwindsor** [comment]
Ah you added these project today! Sorry, I'm 6 hours behind so it's a bit weird.

So if those projects you added have a valid DOI, they should show the contributor list tomorrow after the script runs

**Comment by gabsie** [comment]
I didn't know about this script - that explains the 'citation missing' bit. I am going to dig a little more on Mon.
Gabs

**Comment by ipediez** [comment]
Jacob is taking a look to the issues. @gabsie and @ofanobilbao to chat about this

**Comment by ofanobilbao** [comment]
I will check tomorrow, as there is one test I did (that has no DOI) that did not show in the Catalogue. I did not realise DOI was needed to show up. I have edited today to add a DOI. I'll check tomorrow and if it's there this can be promoted to Production.

**Comment by gabsie** [comment]
I think this worked, @ofanobilbao?
This can now potentially also be on prod.

**Comment by MightyAx** [comment]
@MightyAx to move to production

**Comment by ofanobilbao** [comment]
@jacobwindsor this was all good so Alexie promoted it to Production. However, when testing I came across something else. I have created a ticket and suggested the improvement to Gabs (#606). Gabs will prioritise it when appropriate. I just wanted to let you know

**Comment by jacobwindsor** [comment]
Thanks @ofanobilbao
