### ISSUE TITLE
Fix build job of integration tests

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#605]
The integration test pipeline's build job rebuilds the image of the integration tests and pushes it in the ingest component's quay.io and image.

ebi-ait/dcp-ingest-central/issues#605

Also related to ebi-ait/dcp-ingest-central#571

**Comment by aaclan-ebi** [comment]
I believe I've fixed this. Here are the changes I made: https://github.com/ebi-ait/ingest-integration-tests/compare/893aa9b..11d6774

**Comment by Wkt8** [comment]
@MightyAx to update the ticket

**Comment by MightyAx** [comment]
I [made a change](https://github.com/ebi-ait/ingest-integration-tests/commit/660da17ce02df7a82fe24e4b373e2ef7c2619cf0) to the build configuration to allow manual retrying on integration test builds.
This was important because a failed build meant that integration tests were trying to pull a docker container that did not exist.

Upon making the change the automated build was successful without having to retry and the integration tests began successfully pulling the container.

**Comment by ESapenaVentura** [comment]
@aaclan-ebi pushed some changes but there were issues with gitlab. More investigation is needed, not sure if it's related to this issue.

@MightyAx will create a ticket about the issue
