### ISSUE TITLE
Identifying and wrangling one suitable project from DCP to CellxGene

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#668]
Rewrite as a user story for a wrangler with an outcome.

- [x] Get an example dataset for cellxgene, which was already wrangled by Lattice (input files and JSON metadata, used as input to the flattener) (Jason can point us to its staging area)  @Wkt8 
- [x] Identify one suitable 10x project from DCP (Ingest), which has got all required files for CellxGene @Wkt8 
- [x] Matching up inputs to the flattener to the same entities in HCA schema @Wkt8 
- [ ] document the wrangler steps required for wrangling a project from DCP to CellxGene
- [ ] wrangle a suitable project to the point of handing into the cellxgene dropbox

**Comment by gabsie** [comment]
Take a look here: https://github.com/Lattice-Data/lattice-tools/blob/main/scripts/flattener.py 
See also [341](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/341)

**Comment by Wkt8** [comment]
Example dataset here: https://drive.google.com/drive/folders/1BS2nNwVDg1QKd_MC-zidx_JAyoIKqNrt?usp=sharing 

Jason has zipped up the metadata/data for one matrix, and it should be somewhat similar to a staging are organisation. He has mentioned that we will have to customize the flattener script to look for the local objects rather than objects in the Lattice Portal, in order to work with these. He is open to questions if we have any.

**Comment by idazucchi** [comment]
@Wkt8 to work on this today

**Comment by Wkt8** [comment]
This was more tricky than I thought it'd be, because there is more divergence from our schemas, and also Lattice uses many calculated fields. One thing to note is that I think Lattice is adding additional metadata that cellxgene doesn't actually require (optional), so there may be some things we can ignore. 

HCA to Lattice schema mapping here: https://docs.google.com/spreadsheets/d/1TL4w0P8Vf4hfFDrbuIfkVlPln01S2Ef3/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

**Comment by gabsie** [comment]
A meeting to be set up to discuss this further. @Wkt8

**Comment by Wkt8** [comment]
This is a suitable project: https://data.humancellatlas.org/explore/projects/2ef3655a-973d-4d69-9b41-21fa4041eed7/project-matrices

**Comment by Wkt8** [comment]
Good place to search for examples is: 
Tech: 10x
Species: Human
Files: .tar

**Comment by Wkt8** [comment]
https://data.humancellatlas.org/explore/projects/dc1a41f6-9e09-42a6-959e-3be23db6da56

**Comment by gabsie** [comment]
hey @Wkt8  - this ticket needs to change in Title and Description.. not sure what the work is here, but it still says Lattice flattener?
Is it about finding the suitable project from DCP now?
Thanks!

**Comment by gabsie** [comment]
If about finding suitable projects, there is a ticket 666 for this.

**Comment by ofanobilbao** [comment]
We might end up having different workflows depending on start point file format.

**Comment by ofanobilbao** [comment]
Wei plans to wrangle one project to CellxGene using the current tooling

**Comment by MightyAx** [comment]
Wei has a H5AD file to send!

**Comment by Wkt8** [comment]
Will be discussing with brian and Jason about cell-type ontologies today, and then will submit to cellxgene.

Instructions to submit are as follows from Jason: 
f you go to https://cellxgene.cziscience.com/?curator=true
You should see a Log In option in the upper right
Selecting that and you'll be prompted to log in via Google or GitHub.
After you do that, there should be an option to "Create Collection"
Fill in the Collection information, then it should land you on that newly-created Collection page

**Comment by Wkt8** [comment]
h5ad file submitted to cellxgene in a collection set to private. 
Have notified Jason of this and he will check and get back to us!
Link here: https://cellxgene.cziscience.com/collections/de13e3e2-23b6-40ed-a413-e9e12d7d3910/private

**Comment by ESapenaVentura** [comment]
@Wkt8 may ping jason again

**Comment by gabsie** [comment]
Project is here: https://cellxgene.cziscience.com/collections/de13e3e2-23b6-40ed-a413-e9e12d7d3910/private , Jason continues to take a look
