### ISSUE TITLE
Transform the HCA data and metadata to CellxGene format with the Lattice flattener

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#678]
As a data curator for HCA DCP, I would like to easily transform the metadata and data from ingest in a format suitable for submission to CellxGene. 

see [initial discussion](https://docs.google.com/document/d/1S60Bh2R9mjsEXSqmYYOAfMoFhTWiAOMy0GwuBpJDBPA/edit#heading=h.o3keh5pnoirn)

Acceptance criteria:

Take a look for the flattener here: https://github.com/Lattice-Data/lattice-tools/blob/main/scripts/flattener.py

**Comment by gabsie** [comment]
Take a look here: https://github.com/Lattice-Data/lattice-tools/blob/main/scripts/flattener.py 
- [ ] Dev work (?)
- [ ] Run the 1 example project files through the flattener

**Comment by jacobwindsor** [comment]
I have discovered [this script](https://github.com/ebi-ait/lattice-tools/blob/main/scripts/DCP_mods/DCP_flatten.py) which leads me to think that some work has already begun on this.

Looking at the current script I think automating this will be at least a little complicated because:

- The flattener needs R installed on the local machine
- The flattener is designed to be ran as a script not a module
  - Not just because it is using `__main__` but because `sys.exit` is widely used in the event of errors
- The flattener is not packaged in any way

I have started a fork in `ebi-ait` [here](https://github.com/ebi-ait/lattice-tools/tree/package) to address some of these issues. 

I will need some more information from @Wkt8 as per the input format to the flattener and the mapping between our schema and that

**Comment by gabsie** [comment]
@jacobwindsor has started to investigate this, and needs more info on the mapping of metadata attributes.
will catch up with Amnon if needed additionally on this.

**Comment by jacobwindsor** [comment]
New repo for this https://github.com/ebi-ait/ingest-cellxgene-submitter

**Comment by gabsie** [comment]
The Lattice flattener might need editing from us, let's chat after standup or today about next steps

**Comment by jacobwindsor** [comment]
Closing this in favour of #687
