### ISSUE TITLE
Allow SRP accessions when creating project from GEO accession

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#707]
Relates to #647

Since some projects fail to import grom GEO because of issues with the Entrez API, we can bypass this and import directly from an SRA project accession (SRP or ERP).

It should also allow downloading of a spreadsheet from an SRP or ERP acccession.

**Comment by jacobwindsor** [comment]
PRs

https://github.com/ebi-ait/geo_to_hca/pull/35
https://github.com/ebi-ait/ingest-ui/pull/166
https://github.com/ebi-ait/ingest-broker/pull/39/files

**Comment by ESapenaVentura** [comment]
PR needs one more review, @amnonkhen to review

**Comment by jacobwindsor** [comment]
@ESapenaVentura to test this on staging.

- For a given GEO accession, you should be able to import it with the SRA project accession too
- For a GEO accession that doesn't work because of the Entrez API issue (e.g. GSE189770) you should be able to import it with the relevent SRA project accession
- For a given project, you should be able to download the spreadsheet with the SRA project accession and the GEO accession. Note that the GEO accession might not work because of the Entrez API issue

**Comment by gabsie** [comment]
@ESapenaVentura will test this.

**Comment by ESapenaVentura** [comment]
Hi Jacob! I have been doing a bit more testing:

## GSE189770/SRP348406
### GSE189770
- As expected, didn’t work, but the error message was a bit weird (Printed the object instead of the message)
### SRP348406
- Created project succesfully
- Could download the spreadsheet using the SRP option and it looked alright (for the amount of metadata that you can extract from SRP)

## GSE176509/SRP323456
### GSE176509
- Related to recently opened ticket https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/701
- Did not work and gave a weird error message (Same one as in the ticket)
### SRP323456 
Did not work at all, says:
```verbatim
Unable to import the project due to error: [undefined]. You can still get a spreadsheet to import the project later. We are now generating the spreadsheet, please wait this may take a moment…
```
- After a very long while, this transforms into:
```verbatim
Unable to import the project or download spreadsheet

Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
```

## GSE149313/SRP258346

### GSE149313
- Doesn't work, gives same error as the ops ticket

### SRP258346
- Creates project normally
- Can download spreadsheet
- Tried filling the geo accession and downloading the spreadsheet with the GEO accession, but that doesn't work (I guess it's expected)

## GSE187515/SRP344429

### GSE187515
- Didn't work, same error as in the ops ticket

### SRP344429
- The first time it created a spreadsheet but didn't create a project,
- Then the 2nd time it gave the following error:
```verbatim
Unable to import the project due to error: [There were errors in importing the project: .]. You can still get a spreadsheet to import the project later. We are now generating the spreadsheet, please wait this may take a moment...
```
But ended up creating the spreadsheet anyways but not the project in ingest

## Overall
I have tried looking for a single GEO accession that works but none work. Sometimes the SRP accession will work, but sometimes it just won't either with the errors stated above

**Comment by jacobwindsor** [comment]
PRs for fixes:

https://github.com/ebi-ait/geo_to_hca/pull/36
https://github.com/ebi-ait/ingest-broker/pull/40

**Comment by jacobwindsor** [comment]
The error for `SRP323456` is because geo->HCA is asking for user input and this causes the broker to hang indefinitely until it eventually crashes. The error that you see after a while is the error that happens when broker is down. The same thing now happens for `GSE176509` after my fixes which is to be expected

I will make another ticket for this as it was a preexisting issue

**Comment by jacobwindsor** [comment]
The error for `SRP344429` seems to happen because of a crash or a timeout. It looks like memory usage spikes and sometimes this causes the pod to fail. The error that you get is when ingest-broker is down. It doesn't always fail at exactly the same point and actually, it seems that sometimes the UI times out and a failure doesnt happen. This makes me think it's a memory issue.

The same error now happens for `GSE187515` after my fixes which is to be expected.

I think some consideration into these large projects that take a long time and can cause crashes needs to happen at this point and possibly consider re-designing the architecture for this solution. 

This should be fixed as a seperate task as it was a preexisting issue.

**Comment by ipediez** [comment]
Two issues: one related to GEO expecting user input, another one related to memory usage. The first one should be easier to fix than the second one.

**Comment by jacobwindsor** [comment]
@gabsie  to test

**Comment by gabsie** [comment]
So here is the result of the testing I did.
1. Tried a GSE accession GSE199337 - Unable to find the accession message
2. GSE116672 - took a long time, an error occurred
3. GSE116297 - long time, unable to, error occurred
4. GSE115978 - accession already used by another project, good message

So basically, I have not had any luck. The way I have found accessions is look for projects with single-cell and human on GEO. I have also not found an SRA accession for any of them ![Screenshot 2022-03-28 at 14.55.38.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/bd35c958-fbee-438b-8fec-d731e1cf1819)![Screenshot 2022-03-28 at 14.47.23.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/38812489-a07d-4858-bc4d-ad7a940e4fa7)![Screenshot 2022-03-28 at 14.42.50.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/16d4562c-24b4-4886-b103-ffe960dea6f0)![Screenshot 2022-03-28 at 14.42.06.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/38c4c3d7-3d88-4951-89f8-2e5f49e9e2ab)

So I can discuss further, @jacobwindsor  -let me know if we can catch up briefly.
