### ISSUE TITLE
Project View

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#71]
## User Story
As a wrangler I want to view the project and all the metadata and data that are part of it so that I can confirm the mistake and correct it.

## Acceptance Criteria

A view of showing all the metadata and data files that are associated with a specific project (regardless of which submission they were part of). (for example https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47 is a project with two submissions, all the content should be able to be seen as a single project)
This should be the "current" state of the project and not a historical view of edits that have been made to the project over time. 
Ideally this will be searchable/filterable to make it easier to locate specific metadata/files. (Nice to have in the first instance I think)

**Comment by aaclan-ebi** [comment]
Tasks:
1. [Core]  (new ticket)
- add a project property to biomaterial, process, protocol, file
- add endpoints to retrieve all biomaterials, processes, protocols, files from a project
1.a. Migration work - script + running 
- Can this be done via MongoBee in core? Do we need a separate migration script?
2. [UI] (new ticket) 
- Project page
- UX - needs input from Gabs
3. [Broker] (new ticket) 
- Update the importer to link biomaterial, processes, protcols, files to the project

**Comment by gabsie** [comment]
Hey, everyone
This is the result of our discussions today...
They need further work, but are a good guidance for now
I will also run them by wranglers on Monday and improve, the majority should be fine

![8 1 Project view - Pre submission](https://user-images.githubusercontent.com/19713125/99098424-df9d8600-25d0-11eb-8cc5-bccaea50674c.png)

![8 2 Project view - post-submissnon](https://user-images.githubusercontent.com/19713125/99098405-dc09ff00-25d0-11eb-8070-1e59b877f229.png)

Gabby

**Comment by aaclan-ebi** [comment]
Ah the contacts tabular view is not implemented yet. Do we want to carry over this as task for this sprint?

**Comment by aaclan-ebi** [comment]
I deleted my comment on the contacts tabular view. I remember we just agreed to use the current project view and adding it to this page.

**Comment by gabsie** [comment]
Hi, some review remarks:

I think we need to differentiate between two user scenarios:

1. Journey for when a project gets built/developed: (I realise we can't still have this in this way.. cos that happens right now on the level of submissions)
Project -- Experiment -- Metadata -- Data -- Submit

2. **Journey for when a projects gets reviewed/opened up for updates:**
Project - (Experiment) - Metadata -- Data -- Submissions

So maybe actually we can, even for now - show things without the numbers, and without the Experiment tab, and Submissions to be the last thing.

So can we have this be displayed, actually, with these
**Project - Metadata -- Data -- Submissions**

Any comments? This is like we were discussing before, I realise that. For what we have now (Submissions), it is much clearer.
For the future, when a project/dataset builds up on its own, then we can introduce this Submit step in the middle

Gabs

**Comment by gabsie** [comment]
OK, following @jacobwindsor 's comment, let's keep experiment tab for now.
(for consistency and because that's the way to get a template for submissions for now)

Gabs

**Comment by ami-day** [comment]
I have been testing the project registration and project view pages in ingest staging, and I have found the following:

1. I created a new email address so I can test as a contributor. I made sure this email was not associated with my EBI email, so that I would not be recognised as a wrangler. I tried to register a new project, and when I clicked 'register project', I get this error message:
'https://api.ingest.staging.archive.data.humancellatlas.org/projects/5fb7b58bf423490510b87ed9?partial=true: 403 OK'

2. I initially did some testing of the project view and registration using my EBI email, and it seemed to be working much better using this log in. I took some notes. However, now when I try to log back in using my EBI email to continue testing as a 'wrangler', I am unable to sign in. It recognised me as having logged in using the new 'contributor' email address I created, even though I logged in using this new email using a different internet browser (Safari instead of Google Chrome as usual). 

I am now stuck as to how to continue the testing. Alegria has tried also logging in as a contributor using an alternative email address and gets this same error.

I think it makes sense to work on both the errors I mentioned above before I continue the testing (I am actually unable to continue the testing at this point anyway).

**Comment by clairerye** [comment]
Annoyingly I can't replicate either of these errors! I can log in as either a contributor (gmail) or a wrangler (EBI) and switch between them without issue. This is another thing we can try and bring up with Elixir on Monday.

**Comment by ami-day** [comment]
@aaclan-ebi @clairerye  the tests according to the testing doc. are working as expected (https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/edit#gid=2047502474). There is 1 small issue, though I'm not really sure it is actually an issue, I created a new ticket for it here: https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/101
