### ISSUE TITLE
[Core] Add endpoints to retrieve all biomaterials, processes, protocols, files from a project 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#72]
Dev notes:
We could add a project property to biomaterial, process, protocol, file to easily retrieve the entities but it'll need migration work (can this be done via MongoBee in core? Do we need a separate migration script?)

**Comment by prabh-t** [comment]
@aaclan-ebi let's break this down into steps:
Changes that will not break anything
1. add project property to biomaterial, file, process and protocol
2. add custom `findByProjectId` in each of the repository class of the four entities
3. write a migration script to populate the project property of all existing documents in the database (I personally prefer to do this via a mongo shell script or python)
After this, we should always proceed by first saving the project entity, obtain the uuid, and then set it in the other entities -- so we should always expect to have the project property in POST/PUT/PATCH requests to the biomaterial, file, process and protocol endpoints, otherwise return an error (an entity can't exist on its own). 

4. Add constraint in core to reject entities with project reference (this will help identify any component calling these endpoints)
5. Update component (most likely only/mainly broker is affected)

**Comment by aaclan-ebi** [comment]
Thanks @prabh-t 

> 1. add project property (reference) to biomaterial, file, process and protocol

done 

> 2. add custom findByProjectId in each of the repository class of the corresponding entity

done

> 3. write a migration script to populate the project property of existing documents in the database (I personally prefer to do this via a mongo shell script or python)
After this, we should always proceed by first saving the project entity, obtain the uuid, and then set it in the other entities -- so we should always expect to have the project property in POST/PUT/PATCH requests to the biomaterial, file, process and protocol endpoints, otherwise return an error (an entity can't exist on its own).

> Add constraint in core to reject entities without project reference (this will help identify any component calling these endpoints)

Good point. This is not done yet

> Update component (most likely only/mainly broker is affected)

This is in a different ticket

**Comment by aaclan-ebi** [comment]
@prabh-t I added a new ticket for no. 4 above ebi-ait/dcp-ingest-central#89 as i think it'll require a little more effort. Please see ticket for details.
