### ISSUE TITLE
Update existing metadata/data

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#77]
## User Story
As a wrangler I want to edit existing metadata/data for a project that is already in the DCP so that I can correct mistakes.

## Acceptance Criteria
Corrections to any existing metadata field, including file metadata can be made, revalidated and propagated to Ingest and then exported to the GCP staging area
Information can be added to a field that was previously blank in an existing entity (we could chose to scope this out for now, but will need it as part of additions)
Unchanged data files are not exported as part of updates (as this requires ongoing storage and excess egress costs etc)
An incorrect file can be replaced, revalidated and exported to the GCP staging area (This is an unlikely use case (1 example), so we could chose to scope it out for now, we do need to be able to add additional files as part of additions, to be worked on in a later story)

## Out of scope for this story (but that we will want):
adding a new field that is only in the latest schema

**Comment by clairerye** [comment]
Comments on slack to clarify - 
And would want to clarify whether we can add information to a field that was previously blank in an existing entity

I am pretty sure this is currently allowed, but what if for example we ingest at a particular schema version, then add a field to our schema, will we be able to update that entity to the new version to add the field? (edited) 

I think the 'adding a new field that is only in the latest schema' thing would be used quite often if we want to go back and recurate things, either manually by some kind of migration.
The file thing I guess I wanted to specifically call it out so that if separation of the export of data files and metadata files is implemented, it isn't just that split, but is smarter so that it can see perhaps which data files would need to be exported. I don't see changed data files being something that is used that often when updating/editing (which is what we prioritised this sprint) but more for when are adding new entities (which we decided is out of scope)

**Comment by clairerye** [comment]
I have updated the Acceptance Criteria based on the comments from @mshadbolt. I think there are a couple of acceptance criteria we could choose to put out of scope for this story (but that we definitely do want) if we want to make this story smaller.  
@aaclan-ebi, @prabh-t, @yusra-haider do you want to review and size the story please

**Comment by aaclan-ebi** [comment]
Note here, before we do any updates/reexporting in prod, we should apply the updates done before outside Ingest documented here: https://docs.google.com/document/d/19zeQtnyjCGVS49fMODptUBty83MglrCjywo70mCODG8/edit

**Comment by mshadbolt** [comment]
I think we made all those updates in spreadsheets which we can't currently use to make updates right?

**Comment by clairerye** [comment]
These have been successfully tested end to end - #169 and https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1613736665028000, so changes can now be promoted to production

**Comment by clairerye** [comment]
Unable to update projects that were exported from previous versions of the exporter. 
Also related to #220

**Comment by clairerye** [comment]
@aaclan-ebi can you add details of the issues here about why we are unable to update projects that were exported from previous versions of the exporter.

**Comment by clairerye** [comment]
How do we introduce backwards compatibility to updates?

**Comment by clairerye** [comment]
Closing in favour of using #246 to track this work
