### ISSUE TITLE
Unable to register a new project when logged in as a 'contributor'

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#96]
I have been testing the project registration and project view pages in ingest staging, and I have found the following:

I created a new email address so I can test the project view updates as a contributor. I made sure this email was not associated with my EBI email, so that I would not be recognised as a wrangler. I tried to register a new project, and when I clicked 'register project', I get this error message:
'https://api.ingest.staging.archive.data.humancellatlas.org/projects/5fb7b58bf423490510b87ed9?partial=true: 403 OK'

I am assigning myself to the ticket since I am doing the testing.

**Comment by clairerye** [comment]
Closing this ticket. We have raised this issue with Elixir but have not been able to duplicate it, so will see if we can repeat it as part of normal use/testing.

**Comment by aaclan-ebi** [comment]
I think this is my fault :disappointed:  I believe this has been broken since 2nd Nov 2020 https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#2-november-2020  when i released the change to secure the ingest endpoints. We’re only allowing the contributor to create and not update, so I configured PATCH /projects only allowed for wranglers. But i overlooked that in the form it calls POST and PATCH when the user clicks Next and Register.

Would be nice to add some E2E tests or do manual tests from time to time to catch bugs like this.

**Comment by clairerye** [comment]
Good catch! Clearly I am not a very good tester as I tried to replicate the issue and couldn't on Dec 1st!

**Comment by aaclan-ebi** [comment]
You might be using an account with a wrangler role. I have a quick fix for this. Will just update the config in core endpoints to also allow contributors to update (atleast via API which I believe they won't use). There's no link in the UI for them to access the edit form. So this should be okay for now.

**Comment by aaclan-ebi** [comment]
Actually, I can't exactly remember why we don't allow contributor to do updates to the project once created 🤔

**Comment by clairerye** [comment]
I think we wanted to have a review process, so it should be frozen in that time. But I think that probably needs reviewing, so allowing them to update seems like a the form seems like a good plan to me.

**Comment by clairerye** [comment]
@aaclan-ebi did we fix this by allowing edit access or did we discuss it and then not? Oddly I can't seem to link to the ticket - "Allow contributors to edit the project #55" above

**Comment by aaclan-ebi** [comment]
no, i was trying to fix it but found some issues when testing the fix and I set the PR back to draft for now.
